In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [4]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [6]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [7]:
df.tail()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [8]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [9]:
df["seller_type"].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [11]:
df["fuel"].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [12]:
df["transmission"].unique()

array(['Manual', 'Automatic'], dtype=object)

In [13]:
df["owner"].unique()

array(['First Owner', 'Second Owner', 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'], dtype=object)

In [14]:
# kategorik sütunları seç
categorical_cols = ["fuel", "transmission"]

# one-hot encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

df_encoded.head()

,name,year,selling_price,km_driven,seller_type,owner,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,transmission_Manual
0,Maruti 800 AC,2007,60000,70000,Individual,First Owner,False,False,False,True,True
1,Maruti Wagon R LXI Minor,2007,135000,50000,Individual,First Owner,False,False,False,True,True
2,Hyundai Verna 1.6 SX,2012,600000,100000,Individual,First Owner,True,False,False,False,True
3,Datsun RediGO T Option,2017,250000,46000,Individual,First Owner,False,False,False,True,True
4,Honda Amaze VX i-DTEC,2014,450000,141000,Individual,Second Owner,True,False,False,False,True

In [15]:
df_encoded["age"] = df_encoded["year"]

In [22]:
df_encoded["age"] = 2025 - df_encoded["age"]

In [23]:
df_encoded["age"]

0       18
1       18
2       13
3        8
4       11
        ..
4335    11
4336    11
4337    16
4338     9
4339     9
Name: age, Length: 4340, dtype: int64

In [24]:
df_encoded.corr(numeric_only=True)

,year,selling_price,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,transmission_Manual,age
year,1.000000,0.413922,-0.419688,0.121424,-0.025540,-0.051266,-0.114908,-0.143800,-1.000000
selling_price,0.413922,1.000000,-0.192289,0.282947,-0.005095,-0.042434,-0.269453,-0.530205,-0.413922
km_driven,-0.419688,-0.192289,1.000000,0.285396,-0.001372,0.036652,-0.291139,0.120226,0.419688
fuel_Diesel,0.121424,0.282947,0.285396,1.000000,-0.015063,-0.072422,-0.970934,-0.048098,-0.121424
fuel_Electric,-0.025540,-0.005095,-0.001372,-0.015063,1.000000,-0.001108,-0.014856,-0.044746,0.025540
fuel_LPG,-0.051266,-0.042434,0.036652,-0.072422,-0.001108,1.000000,-0.071427,0.024764,0.051266
fuel_Petrol,-0.114908,-0.269453,-0.291139,-0.970934,-0.014856,-0.071427,1.000000,0.039614,0.114908
transmission_Manual,-0.143800,-0.530205,0.120226,-0.048098,-0.044746,0.024764,0.039614,1.000000,0.143800
age,-1.000000,-0.413922,0.419688,-0.121424,0.025540,0.051266,0.114908,0.143800,1.000000

In [25]:
corr_with_price = df_encoded.corr(numeric_only=True)["selling_price"].sort_values(ascending=False)
corr_with_price.head(15)   # pozitif en yüksek 15

selling_price          1.000000
year                   0.413922
fuel_Diesel            0.282947
fuel_Electric         -0.005095
fuel_LPG              -0.042434
km_driven             -0.192289
fuel_Petrol           -0.269453
age                   -0.413922
transmission_Manual   -0.530205
Name: selling_price, dtype: float64

In [26]:
df_encoded.head()

,name,year,selling_price,km_driven,seller_type,owner,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,transmission_Manual,age
0,Maruti 800 AC,2007,60000,70000,Individual,First Owner,False,False,False,True,True,18
1,Maruti Wagon R LXI Minor,2007,135000,50000,Individual,First Owner,False,False,False,True,True,18
2,Hyundai Verna 1.6 SX,2012,600000,100000,Individual,First Owner,True,False,False,False,True,13
3,Datsun RediGO T Option,2017,250000,46000,Individual,First Owner,False,False,False,True,True,8
4,Honda Amaze VX i-DTEC,2014,450000,141000,Individual,Second Owner,True,False,False,False,True,11

In [31]:
df_encoded = df_encoded.drop(columns=["seller_type","owner","year"])

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ["km_driven", "age", "transmission_Manual", "selling_price","fuel_Diesel","fuel_Petrol","fuel_LPG","fuel_Electric"]  # örnek
df_encoded[num_cols] = scaler.fit_transform(df_encoded[num_cols])

In [33]:
df_encoded

,name,selling_price,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,transmission_Manual,age
0,Maruti 800 AC,-0.767746,0.081139,-0.992196,-0.015181,-0.072992,1.021899,0.339276,1.445074
1,Maruti Wagon R LXI Minor,-0.638096,-0.347689,-0.992196,-0.015181,-0.072992,1.021899,0.339276,1.445074
2,Hyundai Verna 1.6 SX,0.165731,0.724381,1.007865,-0.015181,-0.072992,-0.978571,0.339276,0.258795
3,Datsun RediGO T Option,-0.439300,-0.433455,-0.992196,-0.015181,-0.072992,1.021899,0.339276,-0.927485
4,Honda Amaze VX i-DTEC,-0.093568,1.603479,1.007865,-0.015181,-0.072992,-0.978571,0.339276,-0.215717
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),-0.162716,0.295553,1.007865,-0.015181,-0.072992,-0.978571,0.339276,-0.215717
4336,Hyundai i20 Magna 1.4 CRDi,-0.162716,0.295553,1.007865,-0.015181,-0.072992,-0.978571,0.339276,-0.215717
4337,Maruti 800 AC BSIII,-0.681313,0.359877,-0.992196,-0.015181,-0.072992,1.021899,0.339276,0.970563
4338,Hyundai Creta 1.6 CRDi SX Option,0.623827,0.509967,1.007865,-0.015181,-0.072992,-0.978571,0.339276,-0.690229
4339,Renault KWID RXT,-0.482517,-0.562103,-0.992196,-0.015181,-0.072992,1.021899,0.339276,-0.690229

In [34]:
corr_with_price = df_encoded.corr(numeric_only=True)["selling_price"].sort_values(ascending=False)
corr_with_price.head(15)   # pozitif en yüksek 15

selling_price          1.000000
fuel_Diesel            0.282947
fuel_Electric         -0.005095
fuel_LPG              -0.042434
km_driven             -0.192289
fuel_Petrol           -0.269453
age                   -0.413922
transmission_Manual   -0.530205
Name: selling_price, dtype: float64

In [38]:
y = df["selling_price"]
X = df_encoded.drop(columns=["selling_price"])

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
from sklearn.preprocessing import StandardScaler

# Sadece sayısal kolonları seç
num_cols = X_train.select_dtypes(include=["int64","float64"]).columns

scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols]  = scaler.transform(X_test[num_cols])

In [51]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train[num_cols], y_train)

LinearRegression()

In [53]:
y_pred = model.predict(X_test[num_cols])

In [54]:
y_pred

array([ 4.29280421e+05,  5.34329175e+05,  9.57376739e+04,  5.10672166e+05,
        1.59433360e+06,  2.75577773e+05,  3.96123010e+05,  3.06903255e+05,
        7.06138840e+05,  2.48598221e+05,  6.46656842e+05,  6.17775915e+05,
        6.56072556e+05,  8.05365752e+04,  5.05322312e+05,  4.78731758e+05,
        8.12531681e+05,  1.39406847e+06,  1.00753297e+05,  1.44648868e+06,
        6.82599555e+05,  7.70962480e+05,  4.86616819e+05,  7.94501766e+05,
        3.90983779e+05,  6.56072556e+05,  7.27414802e+05,  2.92236504e+05,
        4.30665714e+05,  5.61399353e+05, -5.24332691e+04,  1.42189015e+06,
        5.52409095e+05,  7.57382089e+05,  5.36683103e+05,  4.70564775e+05,
        8.12156230e+05,  4.98386462e+05,  1.27280295e+05,  5.23102712e+05,
        6.20763628e+05,  4.96621016e+05,  7.44435482e+05,  4.54087276e+05,
        4.55807419e+05,  4.05741135e+05,  4.24147108e+05,  5.23618773e+05,
        7.47423195e+05,  5.03519775e+05,  2.65591782e+05,  3.27545432e+05,
        3.47787442e+05,  2.77479148e+05,  4.44789285e+05,  6.42437425e+05,
        6.97356911e+05,  1.95517105e+05,  3.32513997e+05,  3.76340595e+05,
        2.41600138e+04,  4.97091774e+05,  1.37770869e+06,  6.92649054e+05,
        1.23903711e+04,  3.71726895e+05,  3.47787442e+05,  1.21307801e+05,
        1.90718642e+05,  5.55939988e+05,  1.24667612e+06,  5.04271283e+05,
       -1.11489143e+04,  1.54426732e+06,  3.14390496e+05,  7.39727625e+05,
        2.91032421e+05,  7.36776975e+05,  4.36550535e+05,  6.59070862e+05,
        5.55939988e+05,  6.24566552e+04,  1.89116222e+05,  5.43038711e+05,
       -1.67323194e+05,  4.73552489e+05,  2.91032421e+05,  1.33741829e+05,
        4.07035823e+05, -2.26171407e+05,  5.02738876e+05,  2.33388290e+05,
        2.12655508e+05,  1.86128509e+05,  4.15908358e+05,  4.97091774e+05,
        1.76454202e+06,  2.76093855e+05,  6.50554973e+03,  5.34197927e+05,
        5.47275782e+05,  6.91309090e+05,  1.71617153e+04,  2.80466861e+05,
        2.67425534e+05,  8.62222514e+05,  5.16040926e+05,  3.55674851e+05,
        4.04138715e+05,  4.52270022e+05,  3.25119507e+05,  4.02961751e+05,
        1.50298296e+06,  3.98893584e+05,  4.45966249e+05,  6.94913226e+04,
        2.19011512e+05,  2.15643221e+05,  1.71094367e+06,  6.10077391e+05,
        7.51026482e+05,  3.75981615e+05,  2.52554569e+05,  7.88616944e+05,
        1.42946800e+06, -2.40928763e+05,  9.36915111e+04,  1.39108075e+06,
        2.37371757e+05,  2.65709505e+05,  6.60811014e+05,  7.56205124e+05,
        5.48906449e+05, -1.43783908e+05,  1.37783816e+06,  1.49239029e+06,
        6.70829912e+05,  3.54072431e+05,  5.98519030e+05,  4.39447643e+05,
        3.98893584e+05,  1.03741010e+05,  5.35388416e+05,  3.85850466e+05,
        6.42437425e+05, -2.76264141e+04,  5.34120846e+05,  3.85189563e+05,
        5.95413593e+05,  4.58795133e+05,  4.38188869e+05,  1.39751446e+05,
        8.12156230e+05,  1.41012051e+06,  4.58795133e+05,  5.30798282e+05,
        6.50187735e+05,  1.15510653e+05,  4.20616215e+05,  5.47158058e+05,
        8.38683229e+05,  6.20763628e+05,  5.57116952e+05, -2.88939837e+04,
        4.01151002e+05,  4.47568669e+05,  6.49893494e+05,  4.22198627e+05,
        7.72140113e+04,  3.89173698e+04,  1.14125360e+05,  1.92103936e+05,
        6.20728378e+02,  3.15775789e+05,  4.02934633e+05,  4.99478679e+05,
        5.55514532e+05,  4.10448992e+05,  1.35107108e+05,  5.82466986e+05,
        3.05699172e+05,  1.37288311e+06,  7.98703528e+05,  4.33562822e+05,
        5.30123030e+02,  4.22028545e+05,  1.77346580e+05,  7.84988364e+05,
       -2.02632122e+05,  1.48120912e+06,  5.32400702e+05,  1.44841715e+06,
        7.78024266e+05,  3.45199896e+05,  4.18144778e+04,  7.14197953e+04,
        4.97091774e+05,  2.39389652e+05,  1.53867263e+06,  5.60222389e+05,
        1.41242971e+06,  6.56072556e+05,  5.05964309e+05,  4.91116347e+05,
        2.50952149e+05,  5.70697344e+05, -5.24332691e+04,  9.01606183e+04,
        5.60222389e+05,  8.06271408e+05,  1.42577413e+06,  1.30860265e+06,
        5.82466986e+05,  1.72004938e+05,  3.48187610e+05, -6.12151985e+04,
        1.83231401e+05,  3.43905208e+05,  1.37783816e+06,  3.71726895e+05,
        7.88616944e+05,  1.15510653e+05, -1.01322589e+05,  4.77744285e+05,
        3.78716260e+05, -1.22535064e+05,  1.62615694e+06,  4.38243561e+05,
        6.34010361e+05,  4.82334418e+05,  2.00885865e+05,  9.72135662e+04,
        6.85587268e+05,  5.20748783e+05,  2.45067328e+05,  9.05215243e+05,
        1.53807294e+05,  1.74358866e+05,  6.85587268e+05,  5.14836844e+05,
        3.50333209e+05,  8.15564314e+04,  3.64456780e+05,  4.21793179e+05,
        1.89116222e+05,  7.06138840e+05,  6.73817625e+05,  1.91461891e+05,
        5.38285524e+05,  4.21793179e+05,  3.10655995e+05,  1.77395656e+06,
        3.83496538e+05,  4.15908358e+05,  6.60811014e+05,  2.39389652e+05,
        8.16229341e+04,  3.98912994e+05,  5.52927647e+05,  2.43890364e+05,
        6.44277619e+05,  3.07537040e+05,  1.37783816e+06,  1.07826379e+04,
        2.20233355e+05,  4.55807419e+05,  5.97224342e+05,  5.36747259e+04,
        1.46018679e+06,  1.80832170e+05,  5.82466986e+05,  5.05873703e+05,
        4.04138715e+05,  8.89836540e+04,  4.20498491e+05,  1.76807174e+06,
        6.84953483e+05,  3.49699424e+05,  8.26691739e+05,  6.20763628e+05,
        1.38887808e+06,  4.29280421e+05,  6.35520984e+05,  4.05741135e+05,
        1.23903711e+04,  4.30665714e+05,  6.94369197e+05,  3.25073780e+05,
       -5.24332691e+04,  6.20728378e+02, -1.79092836e+05,  4.42856132e+05,
        1.23903711e+04,  5.94689419e+04,  7.07860105e+04,  7.56205124e+05,
        3.30533145e+05,  3.71726895e+05,  1.37783816e+06,  1.58256396e+06,
        1.35324604e+06, -3.76759131e+04, -1.67323194e+05,  1.61434200e+06,
        1.15510653e+05,  5.58927701e+05, -1.02499553e+05,  1.01323234e+06,
        8.23925873e+05,  3.96959206e+05,  5.32400702e+05,  7.86263016e+05,
        4.30665714e+05,  4.67577062e+05,  3.77493993e+05,  9.74190703e+05,
        6.08993985e+05,  4.58795133e+05,  4.67577062e+05,  1.38887808e+06,
        5.17643346e+05,  5.66434978e+05,  1.66793917e+06,  3.01018433e+05,
       -3.46881997e+04,  4.19050832e+04,  6.26648449e+05,  8.06271408e+05,
        2.47484743e+05,  2.82376496e+05,  6.77100778e+05,  3.08596280e+05,
        4.32901919e+05,  7.25604053e+05,  1.17030409e+06,  3.60844173e+03,
        1.42970532e+04,  3.99946919e+05,  6.03226887e+05,  2.30400577e+05,
        4.67577062e+05,  1.39049938e+05,  4.24147108e+05,  5.14655633e+05,
        3.80599430e+05,  4.23486205e+05,  5.73685057e+05,  5.35388416e+05,
        1.14876868e+05,  5.56691496e+05,  4.06063052e+05,  4.11716562e+05,
        8.12156230e+05,  4.92501641e+05,  1.16012638e+05,  7.36776975e+05,
        6.14788201e+05,  2.75007496e+05,  4.41050063e+05,  5.53160603e+05,
        1.39223478e+06,  2.26027571e+05,  7.32665839e+05,  2.53939863e+05,
        3.03398833e+05,  1.38359351e+06,  1.98253574e+05,  5.88909111e+05,
        6.82599555e+05,  5.16416949e+05,  4.58795133e+05,  4.20498491e+05,
        5.10744587e+05,  3.05608567e+05,  5.17733952e+05,  2.80466861e+05,
        5.45890489e+05,  6.53175448e+05,  6.44302913e+05,  3.83496538e+05,
        6.37150522e+05,  3.40917495e+05,  1.79089664e+05,  4.47568669e+05,
        4.58324374e+05,  4.20498491e+05,  1.47057114e+06,  2.90851211e+05,
        7.59730132e+05,  1.44884261e+06,  5.38828703e+05,  2.42170220e+05,
        6.76171554e+05,  7.06138840e+05,  1.51143004e+06,  7.13834411e+05,
        6.09905534e+05,  4.67740088e+05,  3.02501408e+05,  3.02802064e+05,
        6.08993985e+05,  1.38887808e+06,  4.85231526e+05,  7.20896196e+05,
        6.32533271e+05,  4.15908358e+05, -6.12151985e+04,  3.52687138e+05,
        5.38828703e+05,  1.47288688e+05,  5.81217628e+05,  4.55807419e+05,
        5.65120309e+05,  3.02649144e+05,  5.67709630e+05,  5.04271283e+05,
        1.65486332e+05,  3.18763503e+05,  7.56205124e+05,  1.70623581e+06,
        4.70564775e+05,  2.65709505e+05,  4.76765050e+05,  5.06082032e+05,
        1.46607162e+06,  6.59060269e+05,  3.82161860e+05, -1.11489143e+04,
        1.54834139e+06,  6.08993985e+05,  3.40917495e+05,  1.22997204e+06,
       -5.24332691e+04,  4.70368250e+05,  6.97900090e+05,  1.44959412e+06,
        2.29015284e+05,  5.91339521e+05,  5.40639452e+05,  5.61824809e+05,
        3.60844173e+03,  6.20763628e+05,  3.60844173e+03,  5.94236629e+05,
        3.11067932e+05,  3.88204395e+05,  3.30789724e+05,  1.54019325e+06,
        5.58927701e+05,  1.90718642e+05,  7.32665839e+05,  1.27280295e+05,
        4.22190993e+05,  1.11500068e+05,  2.39182506e+05,  2.74491435e+05,
        4.10023536e+05,  6.32533271e+05,  2.90851211e+05,  4.82026659e+05,
        4.82334418e+05,  4.80731998e+05,  5.25058221e+05, -2.40838158e+05,
        5.14628569e+05,  5.20631060e+05,  6.03109191e+05,  5.85454700e+05,
        6.41315200e+05,  5.57325281e+05,  3.63338664e+05,  3.93971492e+05,
        2.88470616e+05,  8.56337693e+05,  2.71477271e+04,  6.94369197e+05,
        1.89116222e+05,  5.86483387e+05,  2.39389652e+05, -5.39091677e+04,
        3.39876863e+05,  6.08993985e+05,  1.62589224e+05,  5.52952274e+05,
        3.30533145e+05, -3.76759131e+04,  1.08448867e+05,  7.70139782e+05,
        4.76992992e+04,  3.06993860e+05,  5.73685057e+05,  2.65709505e+05,
        1.38947833e+06,  1.38630053e+06,  7.68608552e+05,  8.44568050e+05,
        1.74992651e+05,  5.94236629e+05,  6.32533271e+05,  7.09126553e+05,
       -1.31651844e+05, -4.94455558e+04,  4.04534148e+05,  5.59966960e+05,
        5.74165921e+05,  8.06271408e+05,  7.18452512e+04,  4.11716562e+05,
        5.58927701e+05,  3.45199896e+05,  5.27692845e+05,  1.37770869e+06,
        2.50952149e+05,  6.91309090e+05,  2.86261077e+05,  5.21925747e+05,
        5.97224342e+05,  3.89173698e+04,  1.67382399e+06,  1.74453245e+06,
        1.55409714e+05,  3.39315075e+05,  6.56072556e+05,  4.94108197e+05,
        5.38243153e+05,  6.70829912e+05,  6.44302913e+05,  4.92501641e+05,
        5.67104136e+05,  3.58780288e+05,  9.77655834e+04,  5.05873703e+05,
        1.47390506e+05,  6.32533271e+05,  1.66151117e+06,  3.86727305e+05,
        7.82732123e+05, -7.29848412e+04,  7.56205124e+05,  6.32418038e+05,
        4.94104061e+05,  8.50452871e+05,  5.70697344e+05,  3.05608567e+05,
        1.83711596e+05,  5.20631060e+05,  2.36194793e+05,  2.26208781e+05,
        3.30533145e+05,  6.67549713e+05, -9.07299106e+04,  6.20728378e+02,
        3.33430253e+05,  7.36776975e+05,  5.41182632e+05,  1.55762253e+05,
        1.53807294e+05,  6.85066472e+05,  3.05608567e+05,  4.18896071e+05,
        5.99578271e+05,  1.57138811e+06,  3.25191504e+05,  1.27636973e+06,
        5.67709630e+05, -5.35469832e+03,  6.34524694e+05,  2.40359471e+05,
        2.71477271e+04,  4.45966249e+05,  1.26644024e+06,  8.54527612e+04,
        1.71212063e+06,  3.27545432e+05,  6.94369197e+05,  5.44170345e+05,
        2.62839488e+05,  4.79346705e+05,  2.89248791e+05,  4.42435356e+05,
        1.36062225e+05,  5.05873703e+05,  6.45026746e+05,  5.67709630e+05,
        3.82201850e+05,  2.03873578e+05,  4.19050832e+04,  5.94779809e+05,
        4.52819706e+05,  4.94104061e+05,  7.81684625e+05,  5.82466986e+05,
        6.54443686e+04,  4.04138715e+05,  1.77346580e+05,  2.56836971e+05,
        6.24566552e+04,  5.59986996e+05,  5.16040926e+05,  1.46084764e+06,
        2.88341351e+05,  3.77611716e+05,  3.90558323e+05,  2.52554569e+05,
        4.58795133e+05,  1.70708730e+03,  3.17378210e+05,  4.21793179e+05,
        4.28311785e+05,  2.26212959e+05,  3.09890968e+05,  1.67930865e+05,
        7.33592110e+05, -1.31651844e+05,  5.64569490e+05,  7.47423195e+05,
        8.32798407e+05,  9.42151933e+05,  4.98386462e+05,  4.26501036e+05,
        5.97224342e+05,  8.12156230e+05,  7.29678126e+05,  1.64774011e+06,
        4.30665714e+05,  6.32533271e+05,  9.19713673e+04,  3.30533145e+05,
       -1.13726017e+05,  5.70697344e+05,  1.48768243e+06,  3.82201850e+05,
        7.45352337e+05,  5.14863962e+05,  5.67709630e+05,  2.28409789e+05,
        6.44302913e+05,  2.36756582e+05,  4.67577062e+05, -2.05619835e+05,
        6.56072556e+05,  5.10156105e+05,  2.18630934e+05,  5.28536729e+05,
        1.03107225e+05,  5.17643346e+05,  2.56927576e+05, -3.66384086e+04,
        8.48098943e+05,  3.83496538e+05,  1.74358866e+05,  6.32533271e+05,
        2.88675004e+05,  3.66385253e+05,  2.30400577e+05,  2.11331423e+05,
        5.48452746e+05,  3.79214136e+05,  5.31766917e+05,  5.85454700e+05,
        4.72058343e+05,  4.29488750e+05, -3.66384086e+04,  7.60912981e+05,
        2.83907149e+05,  1.76712795e+05, -3.66384086e+04,  7.49143339e+05,
        3.89173698e+04,  7.42262979e+04,  1.35416940e+06,  2.46171898e+05,
        5.08291793e+05,  1.38887808e+06,  1.68564650e+05,  1.53780844e+04,
        1.31535667e+06,  3.79214136e+05,  4.21793179e+05,  1.34765080e+06,
        2.22177128e+05,  8.00386587e+05,  1.52173090e+05,  3.09890968e+05,
        4.92501641e+05,  6.52541663e+05,  4.45423070e+05,  5.50145772e+05,
        4.76992992e+04,  4.86616819e+05,  8.44568050e+05,  7.51026482e+05,
        1.52422001e+05,  8.94634334e+05,  5.10156105e+05,  7.94501766e+05,
        4.29280421e+05,  6.38418092e+05, -7.29848412e+04,  4.17954500e+05,
        7.07949589e+05,  4.70564775e+05,  3.46892922e+05,  1.55540318e+06,
        1.30268009e+05,  3.15836985e+05,  4.27678000e+05,  6.89661340e+05,
       -7.89602679e+04,  7.67974767e+05,  6.37150522e+05,  1.49420103e+06,
        2.78656112e+05,  5.50145772e+05,  3.54615610e+05,  5.46098818e+05,
        6.20763628e+05,  3.62646031e+05,  2.92118780e+05,  4.55807419e+05,
        3.38110992e+05, -4.06636264e+04,  7.12023661e+05,  1.53249768e+06,
        5.61824809e+05, -1.41366277e+04,  5.48452746e+05,  3.59296565e+04,
        4.53661820e+05,  5.73685057e+05,  8.02017246e+04,  5.03519775e+05,
        1.27917854e+06,  6.60811014e+05,  1.39223478e+06,  6.58969664e+05,
        2.88023571e+05,  3.84673502e+05,  1.33639722e+06, -5.06678227e+04,
        6.16734280e+05,  2.39182506e+05,  5.10156105e+05,  7.16299573e+05,
        1.39049938e+05,  4.77543024e+05,  2.65709505e+05,  4.72058343e+05,
        2.77479148e+05,  4.81908962e+05,  5.86747585e+05,  5.08861417e+05,
        4.19050832e+04,  1.15420047e+05,  4.38152955e+05,  2.89248791e+05,
        5.64178738e+05, -2.67455762e+05,  1.59601510e+05,  9.05215243e+05,
        1.65499257e+06,  4.79527915e+05,  5.67709630e+05,  7.94501766e+05,
       -6.12151985e+04,  1.30507176e+06,  8.76979870e+05,  3.77611716e+05,
        1.80334293e+05,  1.50819581e+05, -3.46881997e+04,  1.65486332e+05,
        7.12023661e+05,  6.37150522e+05,  8.89836540e+04,  2.15643221e+05,
        4.86616819e+05,  7.26781018e+05,  7.82732123e+05,  1.92103936e+05,
        5.79479273e+05,  2.27412864e+05,  2.81010041e+05,  2.78656112e+05,
        5.18394855e+05, -7.66063393e+04,  6.24566552e+04,  2.80466861e+05,
        3.82201850e+05,  3.59957252e+05, -9.42608034e+04,  7.51026482e+05,
        4.22190993e+05,  5.44170345e+05,  4.47143214e+05,  8.18041051e+05,
       -1.99308437e+04,  5.17806372e+05, -1.34820768e+05,  1.03741010e+05,
        5.85454700e+05,  5.56030593e+05,  1.24292582e+05,  5.01917355e+05,
        7.20896196e+05,  4.12377465e+05, -5.06678227e+04,  6.86130448e+05,
       -1.49578124e+05,  5.42567925e+05,  7.95678730e+05,  4.16617441e+05,
        5.36945560e+05,  1.48120912e+06,  3.71183715e+05,  1.24226719e+06,
        8.04630720e+05,  4.86616819e+05,  3.27131120e+05,  7.63266910e+05,
        7.23793304e+05,  6.51774282e+05,  3.60844173e+03,  3.03402963e+05,
        5.70697344e+05,  1.52422001e+05,  4.34622062e+05,  1.48120912e+06,
        1.50819581e+05,  1.70167070e+05,  5.25248311e+05,  5.85997879e+05,
        4.47143214e+05,  1.41012051e+06,  5.46524273e+05,  2.67311925e+05,
        2.41536435e+05,  2.67311925e+05,  7.20896196e+05,  3.42302788e+05,
        1.15510653e+05,  5.60222389e+05, -3.05752403e+05,  5.05873703e+05,
        5.50055166e+05,  5.64694853e+05,  8.56337693e+05,  2.26779079e+05,
        5.94236629e+05,  7.88616944e+05,  3.27545432e+05,  5.36747259e+04,
        8.50452871e+05,  5.66434978e+05, -6.12151985e+04,  1.41835926e+06,
        5.58927701e+05,  1.89116222e+05,  1.60951349e+06, -1.40796195e+05,
        1.64774011e+06,  2.49748067e+05, -1.11489143e+04,  3.59296565e+04,
        5.73685057e+05,  5.14655633e+05,  4.81887199e+05,  5.30798282e+05])

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae  = mean_absolute_error(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2   = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 222742.6193956013
MSE : 184811463397.57117
RMSE: 429897.0381353786
R2  : 0.3943988919472815

In [59]:
df_encoded["selling_price"].describe()

count    4.340000e+03
mean    -9.823171e-18
std      1.000115e+00
min     -8.368925e-01
25%     -5.106080e-01
50%     -2.664340e-01
75%      1.657315e-01
max      1.451363e+01
Name: selling_price, dtype: float64

In [68]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [67]:
df_encoded["brand"] = df["name"].str.split().str[0]
df_encoded.drop(columns=["name"], inplace=True)
df_encoded = pd.get_dummies(df_encoded, columns=["brand"], drop_first=True)

KeyError: "['name'] not found in axis"